apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "twim-bot.fullname" . }}
data:
  config.toml: |-
    {{- $.Files.Get "files/config.toml" | nindent 4 }}
  template.md: |-
    {{- $.Files.Get "files/template.md" | nindent 4 }}
