---
name: TOML linter

on:
  push:
    branches:
      - master
    tags:
      - release-*
    paths-ignore:
      - "site/**/*"
      - schemas/**/*
      - util/**/*
  workflow_dispatch: {}
  pull_request:
    branches:
      - master

jobs:
  taplo:
    name: Check TOML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check TOML compliance
        uses: docker://docker.io/tamasfe/taplo:latest
        with:
          args: check

      - name: lint the formatting
        uses: docker://docker.io/tamasfe/taplo:latest
        with:
          args: format --check --diff
